# Generated by Django 3.2.25 on 2025-02-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testorder',
            name='test_name',
            field=models.CharField(choices=[('histology', 'Histology'), ('cytology', 'Cytology'), ('pbf', 'Peripheral Blood Film'), ('immunohistochemistry', 'immunohistochemistry')], max_length=255, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='macroscopy_description',
            field=models.TextField(verbose_name='Macroscopic Description'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='microscopy_description',
            field=models.TextField(verbose_name='Microscopic Description'),
        ),
    ]
