# Generated by Django 3.2.25 on 2025-02-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_specimen_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionsite',
            options={'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterField(
            model_name='report',
            name='comments_conclusion',
            field=models.TextField(verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnosis and Conclusion'),
        ),
    ]
