# Generated by Django 3.2.25 on 2025-02-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20250223_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='doctor_signature',
        ),
        migrations.AddField(
            model_name='report',
            name='doctor_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/', verbose_name="Doctor's Signature Image"),
        ),
    ]
